routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Guard\ViolationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

 
Route::group(['namespace'=> 'App\Http\Controllers'],function()
{  
    /**
    *  Register 
    */
    Route::get('/register','Auth\RegisterController@show')->name('register.show');
    Route::post('/register', 'Auth\RegisterController@register')->name('register.perform');

    /**
    * Login Routes
    */
    Route::get('/', 'Auth\LoginController@show')->name('login.show');
    Route::get('/login', 'Auth\LoginController@show')->name('login.show');
    Route::post('/login', 'Auth\LoginController@login')->name('login.perform');

    Route::group(['middleware' => ['auth']], function() {
        /**
         * Logout Routes
         */
        Route::get('/logout', 'Auth\LogoutController@perform')->name('logout.perform');
        
        //User Profile
        Route::get('/user-profile', 'Admin\Profile\ProfileController@index')->name('user.profile.index');
        /**
         * Admin Homepage Dashboard
         */
        Route::get('/admin-homepage', 'Admin\Home\HomepageController@index')->name('admin.homepage');        
        /**
         * Guard Homepage Dashboard
         */
        Route::get('/guard-homepage', 'Admin\Home\HomepageController@index')->name('guard.homepage');//same homepage
        Route::get('/guard-homepage-exit', 'Admin\Home\HomepageController@exit')->name('guard.homepageExit');//same homepage
        Route::get('/guard-profile', 'Admin\Profile\ProfileController@index')->name('guard.profile.index');//same admin profile
        Route::get('/guard-events', 'Admin\Events\EventsController@today_events');
        Route::post('/guard-violation', [ViolationController::class, 'report']);
        Route::post('/guard-scan-user-entrance', 'Admin\Home\HomepageController@userEntrance')->name('user.entrance');
        Route::post('/guard-scan-user-exit', 'Admin\Home\HomepageController@userExit')->name('user.exit');
        Route::post('/guard-scan-visitour-entrance', 'Admin\Home\HomepageController@visitourEntrance')->name('visitour.entrance');
        Route::post('/guard-scan-visitour-exit', 'Admin\Home\HomepageController@visitourExit')->name('visitour.exit');
        /**
         * Admin Profile
         */
        
        Route::prefix('admin-profile')->name('admin.profile.')->group(function () {
            Route::get('/', 'Admin\Profile\ProfileController@index')->name('index');
            Route::put('/update/{profile}', 'Admin\Profile\ProfileController@update')->name('update');
            Route::post('/vehicles/store', 'Admin\Users\VehicleController@store')->name('vehicles.store');
            Route::put('/vehicles/update/{vehicle}', 'Admin\Users\VehicleController@update')->name('vehicles.update');
            Route::put('/vehicles/renew/{vehicle}', 'Admin\Users\VehicleController@renew')->name('vehicles.renew');
            Route::delete('/vehicles/delete/{vehicle}', 'Admin\Users\VehicleController@store')->name('vehicles.destroy');
        });
        /**
         * Admin Events
         */
        Route::get('/admin-events', 'Admin\Events\EventsController@index')->name('admin.events');
        Route::get('/admin-events-add', 'Admin\Events\EventsController@create');
        Route::post('/admin-events', 'Admin\Events\EventsController@store');
        Route::get('/admin-events/{event}/edit', 'Admin\Events\EventsController@edit');
        Route::put('/admin-events/{event}', 'Admin\Events\EventsController@update');
        Route::get('/admin-events/{event}', 'Admin\Events\EventsController@destroy');
        Route::get('/admin-events-history', 'Admin\Events\EventsController@history');

        /**
         * Admin Parking Space
         */
        Route::get('/admin-parking-space', 'Admin\ParkingSpace\ParkingSpaceController@index')->name('admin.parking-space');
        Route::get('/admin-parking-space-add', 'Admin\ParkingSpace\ParkingSpaceController@create');
        Route::post('/admin-parking-space', 'Admin\ParkingSpace\ParkingSpaceController@store');
        Route::get('/admin-parking-space/{parking}/edit', 'Admin\ParkingSpace\ParkingSpaceController@edit');
        Route::put('/admin-parking-space/{parking}', 'Admin\ParkingSpace\ParkingSpaceController@update');
        Route::get('/admin-parking-space/{parking}', 'Admin\ParkingSpace\ParkingSpaceController@destroy');
         /**
         * Admin Request
         */
        Route::get('/admin-request', 'Admin\Request\RequestController@index')->name('admin.request');
        Route::put('/admin-request-vehicle/{vehicle}', 'Admin\Request\RequestController@approve_vehicle');
        Route::delete('/admin-request-vehicle/{vehicle}', 'Admin\Request\RequestController@decline_vehicle');

        Route::get('/admin-request-event', 'Admin\Request\RequestController@event')->name('event.request');
        Route::put('/admin-request-event/{event}', 'Admin\Request\RequestController@approve_event');
        Route::delete('/admin-request-event/{event}', 'Admin\Request\RequestController@decline_event');

        Route::get('/admin-request-license', 'Admin\Request\RequestController@license')->name('license.request');
        Route::put('/admin-request-license/{license}', 'Admin\Request\RequestController@approve_license');
        Route::delete('/admin-request-license/{license}', 'Admin\Request\RequestController@decline_license');

        Route::get('/admin-request-visitor', 'Admin\Request\RequestController@visitor')->name('visitor.request');
        Route::put('/admin-request-visitor/{visitor}', 'Admin\Request\RequestController@approvevisitor');
        Route::delete('/admin-request-visitor/{visitor}', 'Admin\Request\RequestController@decline_visitor');

        Route::get('/admin-request-renewal', 'Admin\Request\RequestController@renewal')->name('renewal.request');
        Route::put('/admin-request-renewal/{renewal}', 'Admin\Request\RequestController@approve_renewal');
        Route::delete('/admin-request-renewal/{renewal}', 'Admin\Request\RequestController@decline_renewal');

        Route::get('/admin-userpage', 'Admin\Users\UsersController@index')->name('admin.userpage');
        Route::get('/admin-user-add', 'Admin\Users\UsersController@create');
        Route::post('/admin-userpage/vehicle', 'Admin\Users\UsersController@store_vehicle');
        Route::get('/admin-user-add-vehicle', 'Admin\Users\UsersController@create_vehicle');
        Route::post('/admin-userpage/register', 'Admin\Users\UsersController@store')->name('admin.register');
    });
});

/*

//Route::get('/admin-add-user', function () {
    //return view('admin/user-add_user');
//});

Route::get('/admin-homepage', function () {
    return view('admin-homepage');
});

Route::get('/admin-profile', function () {
    return view('admin/profile');
});

Route::get('/admin-p', function () {
    return view('admin/');
});

Route::get('/admin-events-add', function () {
    return view('admin/events/add');
});

Route::get('/admin-events-update', function () {
    return view('admin/events/update');
});

Route::get('/admin-parking-space', function () {
    return view('admin/parking_space');
});

Route::get('/admin-parking-space-add', function () {
    return view('admin/parking-add');
});

Route::get('/admin-parking-space-update', function () {
    return view('admin/parking-update');
});

Route::get('/admin-request', function () {
    return view('admin/request');
});

Route::get('/admin-request-renewal', function () {
    return view('admin/request-renewal');
});

Route::get('/admin-request-event', function () {
    return view('admin/request-event');
});

Route::get('/admin-request-license', function () {
    return view('admin/request-license');
});


Route::get('/admin-userpage-records', function () {
    return view('admin/user/records');
});

Route::get('/admin-user-record-info-update', function () {
    return view('admin/user/info_update');
});

Route::get('/admin-user-record-license-update', function () {
    return view('admin/user/license_update');
});

Route::get('/admin-user-record-vehicle-update', function () {
    return view('admin/user/vehicle_update');
});

Route::get('/guard-homepage', function () {
    return view('guard/homepage');
});

Route::get('/guard-profile', function () {
    return view('guard/profile');
});
*/

resources/views/modal/personal-info.blade.php
<div class="modal fade bd-example-modal-lg" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">    
        <form action="{{ route('admin.profile.update', ['personal']) }}" method="POST">
            {{ method_field('PUT') }}
            {{ csrf_field() }}
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">PERSONAL INFORMATION</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    @if ($errors->personal->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->personal->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif 
                    <div class="form-row">
                        <div class="form-group col-md-3">
                            <label for="firstname" class="font-weight-bold">FIRSTNAME</label>
                            <input type="text" class="form-control" name="firstname" 
                            {{ isset($user->detail->firstname) ? 'readonly': '' }}  value="{{ $user->detail->firstname ?? '' }}">
                        </div>
                        <div class="form-group col-md-3">
                            <label for="middlename" class="font-weight-bold">MIDDLENAME</label>
                            <input type="text" class="form-control" name="middlename" 
                            {{ isset($user->detail->middlename) ? 'readonly': '' }}  value="{{ $user->detail->middlename ?? '' }}">
                        </div>
                        <div class="form-group col-md-3">
                            <label for="lastname" class="font-weight-bold">SURNAME</label>
                            <input type="text" class="form-control" name="lastname" 
                            {{ isset($user->detail->lastname) ? 'readonly': '' }}  value="{{ $user->detail->lastname ?? '' }}">
                        </div>
                    </div>

                    <div class="form-group col-md-13">
                        <label for="address" class="font-weight-bold">ADDRESS</label>
                        <input type="text" class="form-control" name="address" value="{{ $user->detail->address ?? '' }}">
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-3">
                            <label for="contactno" class="font-weight-bold">CONTACT NUMBER</label>
                            <input type="text" class="form-control" name="contact_number" value="{{ $user->detail->contact_number ?? '' }}">
                        </div>
                        <div class="form-group col-md-3">
                            <label for="emailAddress" class="font-weight-bold">EMAIL ADDRESS</label>
                            <input type="text" class="form-control" name="email" value="{{ $user->email }}">
                        </div>
                        <div class="form-group col-md-3">
                            <label for="username" class="font-weight-bold">USERNAME</label>
                            <input type="text" class="form-control" name="name" value="{{ $user->name }}">
                        </div>
                        <div class="form-group col-md-3">
                            <label for="Password" class="font-weight-bold">PASSWORD</label>
                            <input type="password" placeholder="******" class="form-control" name="password">
                        </div>
                    </div>
                    
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </form>
    </div>
</div>

resources/views/modal/personal-license.blade.php
<div class="modal fade bd-example-modal-lg" id="licenseModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <form action="{{ route('admin.profile.update', ['license']) }}" enctype="multipart/form-data" method="POST">
            {{ method_field('PUT') }}
            {{ csrf_field() }}
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">LICENSE DETAILS</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    @if ($errors->license->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->license->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif 
                    @if ($errors->document->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->document->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif 
                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <label for="DriversLicenseNo" class="font-weight-bold">DRIVERS LICENSE NUMBER</label>
                            <input type="text" class="form-control" id="DriversLicenseNo" name="drivers_license_number" 
                                value="{{ $user->license->drivers_license_number ?? '' }}">
                        </div>

                        <div class="form-group col-md-4">
                            <label for="DriversLicenseExpiry" class="font-weight-bold">DRIVERS LICENSE EXPIRY DATE</label>

                            <div class="form-row">
                                <input class="form-control" type="date" id="" name="drivers_license_expiry" style="width: 250px;"
                                    value="{{ $user->license->drivers_license_expiry ?? '' }}">
                            </div>
                        </div>
                        <div class="form-group col-md-4">
                            <label class="font-weight-bold">TYPE</label>
                            @if(isset($user->license))   
                            <select class="form-control mb-2" name="license_type">
                                <option {{ $user->license->license_type == 'student' ? 'selected' : '' }} value="student">Student Permit</option>
                                <option {{ $user->license->license_type == 'non-prof' ? 'selected': '' }} value="non-prof">Non-Professional</option>
                                <option {{ $user->license->license_type == 'prof' ? 'selected': '' }} value="prof">Professional</option>
                            </select>
                            <input type="hidden" value="{{$user->license->status ?? 2}}" name="status">
                            @else
                            <select class="form-control mb-2" name="license_type">
                                <option value="student">Student Permit</option>
                                <option value="non-prof">Non-Professional</option>
                                <option value="prof">Professional</option>
                            </select>
                            @endif
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="attachedoc" class="font-weight-bold">ATTACH DOCUMENT</label><br>
                            <input type="file" name="document" id="document" required>
                            <!-- <button type="button" class="btn btn-default btn-sm " onclick=""><i class="fas fa-paperclip"></i></button> -->
                        </div>
                    </div>
                    <hr>
                    <!-- <p class="text-center">Upon submitting your application status will will be pending and to be approved</p> -->

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </form>
    </div>
</div>

resources/views/modal/personal-vehicles.blade.php
<div class="modal fade bd-example-modal-lg" id="vehicleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog modal-lg" role="document">
    <form id="regForm" action="/" class="needs-validation" method="POST" id="admin_adduser" required>
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">ADD VEHICLE</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-row">
                        <div class="form-group col-sm-4">
                            <label class="font-weight-bold">PLATE NUMBER</label>
                            <input type="text" name="vehicle_plate_number" class="form-control" id="plateNo" required>
                        </div>

                        <div class="form-group col-sm-4">
                            <label class="font-weight-bold">VEHICLE REGISTRATION NO.</label>
                            <input type="text" name="vehicle_registration_number" class="form-control" id="vehicleRegistrationNo" required>
                        </div>

                        <div class="form-group col-sm-4">
                            <label class="font-weight-bold">EXPIRY DATE</label>
                            <!-- <form action="/action_page.php"> -->
                            <input class="form-control" type="date" id="birthday" name="vehicle_registration_expiry">
                            <!-- </form> -->
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-sm-4">
                            <label class="font-weight-bold">DOCUMENTS</label><br>
                            <input type="file" name="document" id="document" required>
                        </div>

                        <div class="form-group col-sm-4">
                            <label class="font-weight-bold">TYPE</label>
                            <select class="form-control mb-2" name="type" value="" id="vehicleType" placeholder="type" required>
                                <option></option>
                                <option value="vehicle">VEHICLE</option>
                                <option value="motercycle">MOTORCYCLE</option>
                            </select>
                        </div>

                        <div class="form-group col-sm-4">
                            <label class="font-weight-bold">MODEL</label>
                            <input type="text" name="model" value="" class="form-control" id="vehicleModel" required>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-sm-4">
                            <label class="font-weight-bold">COLOR</label>
                            <input type="text" name="color" value="" class="form-control" id="vehicleColor" required>
                        </div>

                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
        </form>
    </div>
</div>

resources/views/modal/report.blade.php
<div class="modal fade" id="reportModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form method="POST" action="/guard-violation">
                @csrf
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">REPORT VIOLATION</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    @if ($errors->report->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->report->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    @endif
                    <div class="mb-3">
                        <label>ENTER PLATE NUMBER</label>
                        <input type="text" class="form-control" name="violation_id" placeholder="">
                        <label>VIOLATION SPECIFICATION</label>
                        <!-- <input type="text" class="form-control" name="specification" placeholder=""> -->
                        <select class="form-control mb-2" name="specification" value="" id="" placeholder="" required>
                            <option></option>
                            <option value="illegal parking">Illegal Parking</option>
                            <option value="overnight parking">Overnight Parking</option>
                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>